---
language: objective-c
env:
  global:
  - secure: DE9IUM+pIV757GU0ccfDJhA752442pKu3DyBthrzHW9+GbsqbfuJOx045CYNN5vOWutFPC0A51B9WxhLNpXXqD3mfU8MhP1gkF7SskrHvcAPrCyfdqZf1Q8XDP5phm2KbHhhwxQMYmmicd6yj8DPNy2wRoSgPSDp/ZUDk51XZDU=
  - secure: AfoHc5tpnYoI2TVGUeE9Xdru+15pd5N4YzO7EWvwmMnrHtNO3retrmKOGpnIyfbP2BeWRTW/z+BI4G0RrfvubjHu2us4wRh6Jq8+UZohBBkM+ldTnyqYHX97q+6ScWBWZGg7dpthd1x/7fmds8dSRzustHUhI7RzPbWEMQH1DGI=
  - NUMJOBS=3
  - EMSCRIPTEN=1
  - EMSCRIPTEN_SHARE_DATA=1
  - EMSCRIPTEN_EMRUN_BROWSER=chrome
  - CCACHE_SLOPPINESS=pch_defines,time_macros
  - CCACHE_COMPRESS=1
  - CCACHE_MAXSIZE=100M
  matrix:
  - URHO3D_LIB_TYPE=STATIC
matrix:
  fast_finish: true
before_script:
- export CI_START_TIME=$(date +%s)
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export TAG=$(git describe --exact-match $TRAVIS_COMMIT 2>/dev/null); if [[ $TAG
  =~ [[:digit:]]+\.[[:digit:]]+ ]]; then export RELEASE_TAG=$TAG; fi
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- if [ $RELEASE_TAG ] || (! [[ $TRAVIS_BRANCH =~ [^-]+-[^-]+-CI ]] && echo $COMMIT_MESSAGE
  |grep -cq '\[ci package\]'); then export PACKAGE_UPLOAD=1; fi
- pushd /usr/bin && sudo ln -sf python python2 && popd
- ulimit -Sn 512
- travis_retry brew update >/dev/null && travis_retry brew install ccache
- if [ $PACKAGE_UPLOAD ]; then travis_retry brew install doxygen graphviz; fi
- wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  && tar xfz emsdk-portable.tar.gz && rm emsdk-portable.tar.gz && cd emsdk_portable
  && ./emsdk update >/dev/null && sed -i.bak 's/-xvf/-xf/g' emsdk && ./emsdk install
  latest >/dev/null && ./emsdk activate latest >/dev/null && source ./emsdk_env.sh
  && export EMSCRIPTEN_ROOT_PATH=$EMSCRIPTEN && export EMSCRIPTEN=1
- export PATH=$(brew info ccache |grep -o '\S*lib\S*'):$EMSCRIPTEN_ROOT_PATH:$PATH
script:
- rake ci
- if [ $PACKAGE_UPLOAD ]; then rake ci_package_upload && rake ci_emscripten_samples_update
  || ! [ $RELEASE_TAG ]; fi
data:
  excluded_sample:
  - 01_HelloWorld
  - 02_HelloGUI
  - 03_Sprites
  - 04_StaticScene
  - 05_AnimatingScene
  - 26_ConsoleInput
  - 29_SoundSynthesis
  - 30_LightAnimation
  - 31_MaterialAnimation
  - 34_DynamicGeometry
  - 35_SignedDistanceFieldText
  - 37_UIDrag
  - 38_SceneAndUILoad
after_script:
- rake ci_delete_mirror
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
    - weitjong@gmail.com
